name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker-linux
        path: target/release/stacker
    
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker-windows
        path: target/release/stacker.exe

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker-mac
        path: target/release/stacker

  build-mac-aarch64:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: rustup target add aarch64-apple-darwin
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --target aarch64-apple-darwin --release
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker-mac-arm
        path: target/release/stacker
