name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker
        path: target/release
    
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker
        path: target/release

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: stacker
        path: target/release
